src/physics-3d/ellipsoid/def.o: src/physics-3d/ellipsoid/def.h
src/physics-3d/ellipsoid/def.o: src/vec/vec.h
src/physics-3d/ellipsoid/def.o: src/vec/vec3.h
src/physics-3d/mesh/boundary/set.o: src/physics-3d/mesh/boundary/set.h
src/physics-3d/mesh/boundary/set.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/mesh/boundary/set.o: src/physics-3d/mesh/node/type.h
src/physics-3d/mesh/boundary/set.o: src/range/def.h
src/physics-3d/mesh/boundary/set.o: src/vec/object3.h
src/physics-3d/mesh/boundary/set.o: src/vec/shape3.h
src/physics-3d/mesh/boundary/set.o: src/vec/vec.h
src/physics-3d/mesh/boundary/set.o: src/vec/vec3.h
src/physics-3d/mesh/boundary/set.o: src/vec/vec4.h
src/physics-3d/mesh/free.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/mesh/free.o: src/physics-3d/mesh/free.h
src/physics-3d/mesh/free.o: src/physics-3d/mesh/node/type.h
src/physics-3d/mesh/free.o: src/physics-3d/mesh/type.h
src/physics-3d/mesh/free.o: src/range/alloc.h
src/physics-3d/mesh/free.o: src/range/def.h
src/physics-3d/mesh/free.o: src/vec/object3.h
src/physics-3d/mesh/free.o: src/vec/shape3.h
src/physics-3d/mesh/free.o: src/vec/vec.h
src/physics-3d/mesh/free.o: src/vec/vec3.h
src/physics-3d/mesh/free.o: src/vec/vec4.h
src/physics-3d/mesh/load.o: src/gltf/type.h
src/physics-3d/mesh/load.o: src/physics-3d/mesh/boundary/set.h
src/physics-3d/mesh/load.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/mesh/load.o: src/physics-3d/mesh/load.h
src/physics-3d/mesh/load.o: src/physics-3d/mesh/node/load.h
src/physics-3d/mesh/load.o: src/physics-3d/mesh/node/type.h
src/physics-3d/mesh/load.o: src/physics-3d/mesh/type.h
src/physics-3d/mesh/load.o: src/range/def.h
src/physics-3d/mesh/load.o: src/vec/object3.h
src/physics-3d/mesh/load.o: src/vec/shape3.h
src/physics-3d/mesh/load.o: src/vec/vec.h
src/physics-3d/mesh/load.o: src/vec/vec3.h
src/physics-3d/mesh/load.o: src/vec/vec4.h
src/physics-3d/mesh/load.o: src/window/def.h
src/physics-3d/mesh/node/load.o: src/gltf/env.h
src/physics-3d/mesh/node/load.o: src/gltf/type.h
src/physics-3d/mesh/node/load.o: src/log/log.h
src/physics-3d/mesh/node/load.o: src/physics-3d/mesh/node/load.h
src/physics-3d/mesh/node/load.o: src/physics-3d/mesh/node/type.h
src/physics-3d/mesh/node/load.o: src/range/alloc.h
src/physics-3d/mesh/node/load.o: src/range/def.h
src/physics-3d/mesh/node/load.o: src/vec/object3.h
src/physics-3d/mesh/node/load.o: src/vec/shape3.h
src/physics-3d/mesh/node/load.o: src/vec/vec.h
src/physics-3d/mesh/node/load.o: src/vec/vec3.h
src/physics-3d/mesh/node/load.o: src/vec/vec4.h
src/physics-3d/mesh/node/load.o: src/window/alloc.h
src/physics-3d/mesh/node/load.o: src/window/def.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/convert/fd/source.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/convert/source.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/convert/type.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/gltf/free.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/gltf/load/source.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/gltf/type.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/log/log.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/physics-3d/mesh/node/load.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/physics-3d/mesh/node/type.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/range/alloc.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/range/def.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/vec/object3.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/vec/shape3.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/vec/vec.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/vec/vec3.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/vec/vec4.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/window/alloc.h
src/physics-3d/mesh/node/test/load-mesh-nodes/load.test.o: src/window/def.h
src/physics-3d/object/set.o: src/gltf/type.h
src/physics-3d/object/set.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/object/set.o: src/physics-3d/mesh/free.h
src/physics-3d/object/set.o: src/physics-3d/mesh/load.h
src/physics-3d/object/set.o: src/physics-3d/mesh/node/type.h
src/physics-3d/object/set.o: src/physics-3d/mesh/type.h
src/physics-3d/object/set.o: src/physics-3d/object/set.h
src/physics-3d/object/set.o: src/physics-3d/object/type.h
src/physics-3d/object/set.o: src/range/alloc.h
src/physics-3d/object/set.o: src/range/def.h
src/physics-3d/object/set.o: src/vec/object3.h
src/physics-3d/object/set.o: src/vec/shape3.h
src/physics-3d/object/set.o: src/vec/vec.h
src/physics-3d/object/set.o: src/vec/vec3.h
src/physics-3d/object/set.o: src/vec/vec4.h
src/physics-3d/object/set.o: src/window/def.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/log/log.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/mesh/node/type.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/mesh/type.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/object/type.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/sweep/moving-ellipsoid-against-mesh.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/sweep/start.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/physics-3d/sweep/type.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/range/def.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/vec/object3.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/vec/shape3.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/vec/vec.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/vec/vec3.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/vec/vec4.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/window/alloc.h
src/physics-3d/sweep/moving-ellipsoid-against-mesh.o: src/window/def.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/log/log.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/mesh/node/type.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/mesh/type.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/object/type.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/sweep/moving-point-against-mesh.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/sweep/start.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/physics-3d/sweep/type.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/range/def.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/vec/object3.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/vec/shape3.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/vec/vec.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/vec/vec3.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/vec/vec4.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/window/alloc.h
src/physics-3d/sweep/moving-point-against-mesh.o: src/window/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/convert/fd/source.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/convert/source.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/convert/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/display.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/free.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/index.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/load/path.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/mesh/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/object/set.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/object/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/shader/free.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/shader/link.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/shader/load/path.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/shader/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/game-interface/init.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/game-interface/time.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/game-interface/window.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/glad/KHR/khrplatform.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/glad/glad.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/gltf/free.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/gltf/load/path.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/gltf/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/keyargs/keyargs.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/log/log.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/mesh/node/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/mesh/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/object/set.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/object/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/sweep/moving-ellipsoid-against-mesh.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/sweep/type.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/range/alloc.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/range/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/thread/benchmark.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/object3.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/shape3.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/vec.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/vec3.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/vec4.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/window/alloc.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/window/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/convert/fd/source.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/convert/source.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/convert/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/display.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/free.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/index.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/load/path.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/mesh/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/object/set.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/object/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/shader/free.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/shader/link.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/shader/load/path.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/shader/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/game-interface/init.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/game-interface/time.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/game-interface/window.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/glad/KHR/khrplatform.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/glad/glad.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/gltf/free.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/gltf/load/path.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/gltf/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/keyargs/keyargs.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/log/log.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/mesh/boundary/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/mesh/node/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/mesh/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/object/set.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/object/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/sweep/moving-point-against-mesh.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/sweep/type.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/range/alloc.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/range/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/thread/benchmark.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/object3.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/shape3.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/vec.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/vec3.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/vec4.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/window/alloc.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/window/def.h
