src/physics-3d/def.o: src/physics-3d/def.h
src/physics-3d/def.o: src/range/alloc.h
src/physics-3d/def.o: src/range/def.h
src/physics-3d/def.o: src/vec/object3.h
src/physics-3d/def.o: src/vec/shape3.h
src/physics-3d/def.o: src/vec/vec.h
src/physics-3d/def.o: src/vec/vec3.h
src/physics-3d/def.o: src/vec/vec4.h
src/physics-3d/def.o: src/window/alloc.h
src/physics-3d/def.o: src/window/def.h
src/physics-3d/ellipsoid/def.o: src/physics-3d/ellipsoid/def.h
src/physics-3d/ellipsoid/def.o: src/vec/vec.h
src/physics-3d/ellipsoid/def.o: src/vec/vec3.h
src/physics-3d/mesh.o: src/gltf/def.h
src/physics-3d/mesh.o: src/gltf/env.h
src/physics-3d/mesh.o: src/log/log.h
src/physics-3d/mesh.o: src/physics-3d/def.h
src/physics-3d/mesh.o: src/physics-3d/mesh.h
src/physics-3d/mesh.o: src/physics-3d/sweep.h
src/physics-3d/mesh.o: src/range/alloc.h
src/physics-3d/mesh.o: src/range/def.h
src/physics-3d/mesh.o: src/vec/object3.h
src/physics-3d/mesh.o: src/vec/shape3.h
src/physics-3d/mesh.o: src/vec/vec.h
src/physics-3d/mesh.o: src/vec/vec2.h
src/physics-3d/mesh.o: src/vec/vec3.h
src/physics-3d/mesh.o: src/vec/vec4.h
src/physics-3d/mesh.o: src/window/alloc.h
src/physics-3d/mesh.o: src/window/def.h
src/physics-3d/object.o: src/gltf/def.h
src/physics-3d/object.o: src/log/log.h
src/physics-3d/object.o: src/physics-3d/def.h
src/physics-3d/object.o: src/physics-3d/mesh.h
src/physics-3d/object.o: src/physics-3d/object.h
src/physics-3d/object.o: src/physics-3d/sweep.h
src/physics-3d/object.o: src/range/def.h
src/physics-3d/object.o: src/vec/object3.h
src/physics-3d/object.o: src/vec/shape3.h
src/physics-3d/object.o: src/vec/vec.h
src/physics-3d/object.o: src/vec/vec3.h
src/physics-3d/object.o: src/vec/vec4.h
src/physics-3d/object.o: src/window/def.h
src/physics-3d/set_hull.o: src/gltf/def.h
src/physics-3d/set_hull.o: src/log/log.h
src/physics-3d/set_hull.o: src/physics-3d/def.h
src/physics-3d/set_hull.o: src/physics-3d/mesh.h
src/physics-3d/set_hull.o: src/physics-3d/set_hull.h
src/physics-3d/set_hull.o: src/range/alloc.h
src/physics-3d/set_hull.o: src/range/def.h
src/physics-3d/set_hull.o: src/vec/object3.h
src/physics-3d/set_hull.o: src/vec/shape3.h
src/physics-3d/set_hull.o: src/vec/vec.h
src/physics-3d/set_hull.o: src/vec/vec3.h
src/physics-3d/set_hull.o: src/vec/vec4.h
src/physics-3d/set_hull.o: src/window/alloc.h
src/physics-3d/set_hull.o: src/window/def.h
src/physics-3d/sweep.o: src/physics-3d/def.h
src/physics-3d/sweep.o: src/physics-3d/sweep.h
src/physics-3d/sweep.o: src/range/def.h
src/physics-3d/sweep.o: src/vec/object3.h
src/physics-3d/sweep.o: src/vec/shape3.h
src/physics-3d/sweep.o: src/vec/vec.h
src/physics-3d/sweep.o: src/vec/vec3.h
src/physics-3d/sweep.o: src/vec/vec4.h
src/physics-3d/sweep.o: src/window/alloc.h
src/physics-3d/sweep.o: src/window/def.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/convert/fd/source.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/convert/source.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/convert/status.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/gltf/convert.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/gltf/def.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/gltf/parse.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/log/log.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/physics-3d/def.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/physics-3d/mesh.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/range/def.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/vec/object3.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/vec/shape3.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/vec/vec.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/vec/vec3.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/vec/vec4.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/window/alloc.h
src/physics-3d/test/load-mesh-nodes/load.test.o: src/window/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/convert/fd/source.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/convert/source.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/convert/status.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/draw.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/buffer/loader.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/mesh/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/shader/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/draw-3d/shader/load.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/game-interface/init.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/game-interface/time.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/game-interface/window.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/glad/KHR/khrplatform.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/glad/glad.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/gltf/convert.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/gltf/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/gltf/parse.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/keyargs/keyargs.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/log/log.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/mesh.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/object.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/set_hull.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/physics-3d/sweep.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/range/alloc.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/range/def.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/object3.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/shape3.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/vec.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/vec3.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/vec/vec4.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/window/alloc.h
src/physics-3d/test/visual-mesh-sweep-sphere/test.o: src/window/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/convert/fd/source.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/convert/source.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/convert/status.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/draw.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/buffer/loader.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/mesh/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/shader/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/draw-3d/shader/load.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/game-interface/init.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/game-interface/time.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/game-interface/window.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/glad/KHR/khrplatform.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/glad/glad.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/gltf/convert.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/gltf/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/gltf/parse.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/keyargs/keyargs.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/log/log.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/mesh.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/object.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/set_hull.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/physics-3d/sweep.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/range/alloc.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/range/def.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/object3.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/shape3.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/vec.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/vec3.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/vec/vec4.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/window/alloc.h
src/physics-3d/test/visual-mesh-traceline/test.o: src/window/def.h
